CREATE TABLE departments (
  id SERIAL PRIMARY KEY,
  name VARCHAR
)


--- role
CREATE TYPE WORKER_ROLE AS ENUM('DIREKTOR', 'BUXGALTER', 'DIZAYNER', 'DASTURCHI');

-- WORKERS 
CREATE TABLE IF NOT EXISTS WORKERS (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  role WORKER_ROLE NOT NULL,
  salary DECIMAL NOT NULL DEFAULT 0,
  department_id INT NOT NULL,
  references departments (id)
  );

